FROM docker.io/library/golang:1.27 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags=-s -o /controlplane ./cmd/controlplane

FROM docker.io/library/debian:trixie-slim
ARG TERRAFORM_VERSION=1.13.3
ARG PACKER_VERSION=1.14.2
RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates git openssh-client procps unzip curl ansible-core \
 && curl -fsSLo /tmp/tf.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
 && curl -fsSLo /tmp/packer.zip https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip \
 && unzip -d /usr/local/bin /tmp/tf.zip terraform \
 && unzip -d /usr/local/bin /tmp/packer.zip packer \
 && rm /tmp/*.zip && apt-get purge -y unzip curl && apt-get autoremove -y && rm -rf /var/lib/apt/lists/* \
 && useradd --system --home-dir /var/lib/controlplane --create-home controlplane
COPY --from=build /controlplane /usr/local/bin/controlplane
USER controlplane
VOLUME /var/lib/controlplane
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/controlplane", "-config", "/etc/controlplane/catalog.yml", "-data-dir", "/var/lib/controlplane", "-listen", "0.0.0.0:8080"]
